# Generated by Django 4.2.4 on 2023-11-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helmets', '0002_alter_customer_phone_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qnty',
        ),
    ]
