# Generated by Django 4.2.4 on 2023-11-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcolor',
            field=models.CharField(default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='add_product/'),
        ),
    ]
